-- Schema PostgreSQL derivado do modelo enviado nas imagens.
-- Execute em um banco vazio ou como uma migration inicial.
--
-- Assumptions:
--   * numeric, text and timestamptz are used for the diagram's decimal,
--     string and datetime types.
--   * pessoa is also used for usuario_id and avaliador_id because the model
--     does not contain a separate usuario/avaliador table.
--   * The circular references between template_planilha and
--     cliente_tipo_laudo, and between email_classificacao and ordem_servico,
--     are added after both tables exist.

BEGIN;

CREATE TABLE campo_canonico (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              varchar(100) NOT NULL UNIQUE,
    rotulo              text NOT NULL,
    tipo_dado           varchar(50) NOT NULL,
    unidade             varchar(50)
);

CREATE TABLE conta_email (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endereco                varchar(320) NOT NULL UNIQUE,
    provedor                text NOT NULL,
    ultima_sincronizacao    timestamptz
);

CREATE TABLE cliente (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj                    varchar(18) NOT NULL UNIQUE,
    razao_social            text NOT NULL,
    sla_padrao_horas        integer NOT NULL CHECK (sla_padrao_horas > 0),
    janela_contato_inicio  time,
    janela_contato_fim     time,
    CONSTRAINT cliente_janela_contato_ck CHECK (
        janela_contato_inicio IS NULL
        OR janela_contato_fim IS NULL
        OR janela_contato_inicio < janela_contato_fim
    )
);

CREATE TABLE tipo_laudo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  varchar(100) NOT NULL UNIQUE,
    nome                    text NOT NULL,
    exige_vistoria          boolean NOT NULL DEFAULT false,
    exige_pesquisa_amostral boolean NOT NULL DEFAULT false
);

CREATE TABLE tipologia (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    varchar(100) NOT NULL UNIQUE
);

CREATE TABLE pessoa (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    text NOT NULL,
    documento               varchar(30),
    telefone_principal      varchar(30),
    email                   varchar(320),
    preferencia_contato     varchar(30)
);

CREATE TABLE vistoriador (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    text NOT NULL,
    registro_profissional   varchar(50),
    base_latitude           numeric,
    base_longitude          numeric,
    capacidade_diaria       integer NOT NULL DEFAULT 1 CHECK (capacidade_diaria > 0),
    ativo                   boolean NOT NULL DEFAULT true,
    CONSTRAINT vistoriador_latitude_ck CHECK (
        base_latitude IS NULL OR base_latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT vistoriador_longitude_ck CHECK (
        base_longitude IS NULL OR base_longitude BETWEEN -180 AND 180
    )
);

CREATE TABLE fonte_pesquisa (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    varchar(100) NOT NULL,
    tipo                    varchar(30) NOT NULL CHECK (tipo IN ('oferta', 'transacao')),
    confiabilidade          numeric NOT NULL CHECK (confiabilidade BETWEEN 0 AND 1)
);

CREATE TABLE email_recebido (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_email_id          integer NOT NULL REFERENCES conta_email(id),
    message_id              text NOT NULL UNIQUE,
    remetente               varchar(320) NOT NULL,
    assunto                 text,
    corpo_texto             text,
    recebido_em             timestamptz NOT NULL,
    status_processamento    varchar(50) NOT NULL
);

CREATE TABLE email_anexo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_recebido_id       integer NOT NULL REFERENCES email_recebido(id),
    nome_arquivo            text NOT NULL,
    caminho_armazenamento   text NOT NULL,
    texto_extraido          text
);

CREATE TABLE regra_captacao (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id              integer NOT NULL REFERENCES cliente(id),
    tipo_laudo_id           integer NOT NULL REFERENCES tipo_laudo(id),
    versao                  integer NOT NULL CHECK (versao > 0),
    criterio_remetente      text,
    criterio_assunto        text,
    vigente_de              date NOT NULL,
    vigente_ate             date,
    CONSTRAINT regra_captacao_vigencia_ck CHECK (
        vigente_ate IS NULL OR vigente_ate >= vigente_de
    ),
    CONSTRAINT regra_captacao_versao_uq UNIQUE (cliente_id, tipo_laudo_id, versao)
);

CREATE TABLE regra_campo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regra_captacao_id       integer NOT NULL REFERENCES regra_captacao(id),
    campo_canonico          varchar(100) NOT NULL REFERENCES campo_canonico(codigo)
        ON UPDATE CASCADE,
    origem                  varchar(20) NOT NULL CHECK (origem IN ('corpo', 'assunto', 'anexo')),
    expressao               text NOT NULL,
    obrigatorio             boolean NOT NULL DEFAULT false,
    CONSTRAINT regra_campo_uq UNIQUE (regra_captacao_id, campo_canonico, origem)
);

CREATE TABLE email_classificacao (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_recebido_id       integer NOT NULL REFERENCES email_recebido(id),
    regra_captacao_id       integer NOT NULL REFERENCES regra_captacao(id),
    ordem_servico_id        integer,
    confianca               numeric CHECK (confianca BETWEEN 0 AND 1),
    decidido_por            varchar(20) NOT NULL CHECK (decidido_por IN ('auto', 'humano'))
);

CREATE TABLE extracao_campo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_classificacao_id  integer NOT NULL REFERENCES email_classificacao(id),
    campo_canonico          varchar(100) NOT NULL REFERENCES campo_canonico(codigo)
        ON UPDATE CASCADE,
    valor_bruto             text,
    valor_normalizado       text,
    confianca               numeric CHECK (confianca BETWEEN 0 AND 1),
    corrigido_por_usuario_id integer REFERENCES pessoa(id)
);

CREATE TABLE cliente_tipo_laudo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id              integer NOT NULL REFERENCES cliente(id),
    tipo_laudo_id           integer NOT NULL REFERENCES tipo_laudo(id),
    template_planilha_id    integer,
    sla_horas               integer CHECK (sla_horas > 0),
    min_amostras            integer CHECK (min_amostras >= 0),
    raio_pesquisa_max_metros integer CHECK (raio_pesquisa_max_metros > 0),
    CONSTRAINT cliente_tipo_laudo_uq UNIQUE (cliente_id, tipo_laudo_id)
);

CREATE TABLE template_planilha (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_tipo_laudo_id   integer NOT NULL REFERENCES cliente_tipo_laudo(id),
    versao                  integer NOT NULL CHECK (versao > 0),
    formato                 varchar(20) NOT NULL CHECK (formato IN ('xlsx', 'pdf', 'api')),
    arquivo_modelo          text,
    vigente_de              date NOT NULL,
    vigente_ate             date,
    CONSTRAINT template_planilha_vigencia_ck CHECK (
        vigente_ate IS NULL OR vigente_ate >= vigente_de
    ),
    CONSTRAINT template_planilha_versao_uq UNIQUE (cliente_tipo_laudo_id, versao)
);

ALTER TABLE cliente_tipo_laudo
    ADD CONSTRAINT cliente_tipo_laudo_template_fk
    FOREIGN KEY (template_planilha_id) REFERENCES template_planilha(id);

CREATE TABLE template_campo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_planilha_id    integer NOT NULL REFERENCES template_planilha(id),
    campo_canonico_id       integer NOT NULL REFERENCES campo_canonico(id),
    destino                 text NOT NULL,
    rotulo_cliente          text,
    obrigatorio             boolean NOT NULL DEFAULT false,
    formato_saida           text,
    CONSTRAINT template_campo_uq UNIQUE (template_planilha_id, campo_canonico_id)
);

CREATE TABLE regra_negocio_cliente (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_tipo_laudo_id   integer NOT NULL REFERENCES cliente_tipo_laudo(id),
    descricao               text NOT NULL,
    campo_alvo              varchar(100) NOT NULL,
    operador                varchar(30) NOT NULL,
    valor_referencia        text,
    severidade              varchar(20) NOT NULL CHECK (severidade IN ('bloqueia', 'alerta'))
);

CREATE TABLE imovel (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep                     varchar(9),
    logradouro              text,
    numero                  varchar(30),
    bairro                  text,
    cidade                  text,
    uf                      char(2),
    latitude                numeric,
    longitude               numeric,
    matricula               varchar(100),
    tipologia_id            integer REFERENCES tipologia(id),
    area_terreno            numeric,
    area_construida         numeric,
    quartos                 integer CHECK (quartos >= 0),
    vagas                   integer CHECK (vagas >= 0),
    ano_construcao          integer,
    estado_conservacao      varchar(50),
    CONSTRAINT imovel_latitude_ck CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT imovel_longitude_ck CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    ),
    CONSTRAINT imovel_area_terreno_ck CHECK (area_terreno IS NULL OR area_terreno >= 0),
    CONSTRAINT imovel_area_construida_ck CHECK (area_construida IS NULL OR area_construida >= 0)
);

CREATE TABLE ordem_servico (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_os_cliente       varchar(100) NOT NULL,
    cliente_id              integer NOT NULL REFERENCES cliente(id),
    tipo_laudo_id           integer NOT NULL REFERENCES tipo_laudo(id),
    email_recebido_id       integer REFERENCES email_recebido(id),
    imovel_id               integer REFERENCES imovel(id),
    recebida_em             timestamptz NOT NULL,
    prazo_entrega           timestamptz,
    status                  varchar(50) NOT NULL,
    CONSTRAINT ordem_servico_numero_uq UNIQUE (cliente_id, numero_os_cliente)
);

ALTER TABLE email_classificacao
    ADD CONSTRAINT email_classificacao_os_fk
    FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico(id);

CREATE TABLE evento_os (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id        integer NOT NULL REFERENCES ordem_servico(id),
    status_anterior         varchar(50),
    status_novo             varchar(50) NOT NULL,
    motivo                  text,
    usuario_id              integer REFERENCES pessoa(id),
    ocorrido_em             timestamptz NOT NULL
);

CREATE TABLE os_pessoa (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id        integer NOT NULL REFERENCES ordem_servico(id),
    pessoa_id               integer NOT NULL REFERENCES pessoa(id),
    papel                   varchar(50) NOT NULL,
    principal_para_contato  boolean NOT NULL DEFAULT false,
    CONSTRAINT os_pessoa_uq UNIQUE (ordem_servico_id, pessoa_id, papel)
);

CREATE TABLE imovel_atributo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id               integer NOT NULL REFERENCES imovel(id),
    campo_canonico_id       integer NOT NULL REFERENCES campo_canonico(id),
    valor                   text NOT NULL,
    CONSTRAINT imovel_atributo_uq UNIQUE (imovel_id, campo_canonico_id)
);

CREATE TABLE agenda_disponibilidade (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoriador_id          integer NOT NULL REFERENCES vistoriador(id),
    data                    date NOT NULL,
    hora_inicio             time NOT NULL,
    hora_fim                time NOT NULL,
    tipo                    varchar(30) NOT NULL,
    capacidade_restante     integer NOT NULL CHECK (capacidade_restante >= 0),
    CONSTRAINT agenda_disponibilidade_horario_ck CHECK (hora_inicio < hora_fim)
);

CREATE TABLE vistoriador_regiao (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoriador_id          integer NOT NULL REFERENCES vistoriador(id),
    tipo_area               varchar(30) NOT NULL,
    valor                   text NOT NULL,
    CONSTRAINT vistoriador_regiao_uq UNIQUE (vistoriador_id, tipo_area, valor)
);

CREATE TABLE vistoria (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id        integer NOT NULL REFERENCES ordem_servico(id),
    vistoriador_id          integer NOT NULL REFERENCES vistoriador(id),
    data_hora_estimada      timestamptz,
    status                  varchar(50) NOT NULL,
    agendado_por            varchar(20) CHECK (agendado_por IN ('automatico', 'humano')),
    realizada_em            timestamptz,
    motivo_improdutiva      text
);

CREATE TABLE tentativa_contato (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id             integer NOT NULL REFERENCES vistoria(id),
    pessoa_id               integer NOT NULL REFERENCES pessoa(id),
    canal                   varchar(30) NOT NULL,
    tentado_em              timestamptz NOT NULL,
    resultado               text,
    proxima_tentativa_em    timestamptz
);

CREATE TABLE vistoria_foto (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id             integer NOT NULL REFERENCES vistoria(id),
    caminho_armazenamento   text NOT NULL,
    categoria               varchar(50),
    capturada_em            timestamptz NOT NULL
);

CREATE TABLE coleta (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte_pesquisa_id       integer NOT NULL REFERENCES fonte_pesquisa(id),
    iniciada_em             timestamptz NOT NULL,
    parametros              text,
    total_coletado          integer NOT NULL DEFAULT 0 CHECK (total_coletado >= 0),
    total_novo              integer NOT NULL DEFAULT 0 CHECK (total_novo >= 0),
    total_duplicado         integer NOT NULL DEFAULT 0 CHECK (total_duplicado >= 0),
    executada_por           varchar(20) NOT NULL CHECK (executada_por IN ('robo', 'manual'))
);

CREATE TABLE amostra (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte_pesquisa_id       integer NOT NULL REFERENCES fonte_pesquisa(id),
    coleta_id               integer NOT NULL REFERENCES coleta(id),
    identificador_externo   varchar(255) NOT NULL,
    url                     text,
    coletado_em             timestamptz NOT NULL,
    tipo_negocio            varchar(20) NOT NULL CHECK (tipo_negocio IN ('venda', 'locacao')),
    natureza                varchar(20) NOT NULL CHECK (natureza IN ('oferta', 'transacao')),
    valor_total             numeric CHECK (valor_total >= 0),
    area_total              numeric CHECK (area_total >= 0),
    latitude                numeric,
    longitude               numeric,
    tipologia_id            integer REFERENCES tipologia(id),
    quartos                 integer CHECK (quartos >= 0),
    vagas                   integer CHECK (vagas >= 0),
    status_validacao        varchar(50) NOT NULL,
    CONSTRAINT amostra_identificador_uq UNIQUE (fonte_pesquisa_id, identificador_externo),
    CONSTRAINT amostra_latitude_ck CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT amostra_longitude_ck CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

CREATE TABLE amostra_atributo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amostra_id              integer NOT NULL REFERENCES amostra(id),
    campo_canonico_id       integer NOT NULL REFERENCES campo_canonico(id),
    valor                   text NOT NULL,
    CONSTRAINT amostra_atributo_uq UNIQUE (amostra_id, campo_canonico_id)
);

CREATE TABLE laudo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id        integer NOT NULL REFERENCES ordem_servico(id),
    vistoria_id             integer REFERENCES vistoria(id),
    avaliador_id            integer REFERENCES pessoa(id),
    template_planilha_id    integer REFERENCES template_planilha(id),
    data_base               date NOT NULL,
    metodologia             text,
    valor_avaliacao         numeric CHECK (valor_avaliacao >= 0),
    valor_terreno           numeric CHECK (valor_terreno >= 0),
    valor_benfeitorias      numeric CHECK (valor_benfeitorias >= 0),
    grau_fundamentacao      varchar(50),
    status                  varchar(50) NOT NULL
);

CREATE TABLE laudo_amostra (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo_id                integer NOT NULL REFERENCES laudo(id),
    amostra_id              integer NOT NULL REFERENCES amostra(id),
    distancia_metros        numeric CHECK (distancia_metros >= 0),
    area_considerada        numeric CHECK (area_considerada >= 0),
    fator_oferta            numeric,
    fator_fonte             numeric,
    fator_transposicao      numeric,
    fator_area              numeric,
    fator_idade             numeric,
    valor_homogeneizado     numeric,
    utilizada_no_calculo    boolean NOT NULL DEFAULT true,
    motivo_exclusao         text,
    CONSTRAINT laudo_amostra_uq UNIQUE (laudo_id, amostra_id)
);

CREATE TABLE laudo_versao (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo_id                integer NOT NULL REFERENCES laudo(id),
    numero_versao           integer NOT NULL CHECK (numero_versao > 0),
    motivo_revisao           text,
    dados_snapshot          jsonb,
    criada_em               timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT laudo_versao_uq UNIQUE (laudo_id, numero_versao)
);

CREATE TABLE laudo_arquivo (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo_id                integer NOT NULL REFERENCES laudo(id),
    laudo_versao_id         integer NOT NULL REFERENCES laudo_versao(id),
    tipo                    varchar(20) NOT NULL CHECK (tipo IN ('planilha', 'pdf', 'art')),
    caminho_armazenamento   text NOT NULL,
    hash                    varchar(255) NOT NULL
);

CREATE TABLE laudo_validacao (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo_id                integer NOT NULL REFERENCES laudo(id),
    regra_negocio_cliente_id integer NOT NULL REFERENCES regra_negocio_cliente(id),
    resultado               varchar(20) NOT NULL CHECK (resultado IN ('aprovado', 'alerta', 'reprovado')),
    mensagem                text,
    verificado_em           timestamptz NOT NULL
);

CREATE TABLE entrega (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo_id                integer NOT NULL REFERENCES laudo(id),
    laudo_versao_id         integer NOT NULL REFERENCES laudo_versao(id),
    canal                   varchar(20) NOT NULL CHECK (canal IN ('email', 'portal', 'api')),
    enviado_em              timestamptz,
    protocolo_cliente       text,
    status                  varchar(50) NOT NULL,
    motivo_recusa           text
);

-- Foreign-key indexes. UNIQUE constraints above already create their own indexes.
CREATE INDEX email_recebido_conta_email_idx ON email_recebido (conta_email_id);
CREATE INDEX email_anexo_email_recebido_idx ON email_anexo (email_recebido_id);
CREATE INDEX regra_captacao_cliente_tipo_idx ON regra_captacao (cliente_id, tipo_laudo_id);
CREATE INDEX regra_campo_regra_idx ON regra_campo (regra_captacao_id);
CREATE INDEX email_classificacao_email_idx ON email_classificacao (email_recebido_id);
CREATE INDEX email_classificacao_regra_idx ON email_classificacao (regra_captacao_id);
CREATE INDEX email_classificacao_os_idx ON email_classificacao (ordem_servico_id);
CREATE INDEX extracao_campo_classificacao_idx ON extracao_campo (email_classificacao_id);
CREATE INDEX extracao_campo_usuario_idx ON extracao_campo (corrigido_por_usuario_id);
CREATE INDEX cliente_tipo_laudo_cliente_idx ON cliente_tipo_laudo (cliente_id);
CREATE INDEX cliente_tipo_laudo_tipo_idx ON cliente_tipo_laudo (tipo_laudo_id);
CREATE INDEX cliente_tipo_laudo_template_idx ON cliente_tipo_laudo (template_planilha_id);
CREATE INDEX template_planilha_cliente_tipo_idx ON template_planilha (cliente_tipo_laudo_id);
CREATE INDEX template_campo_template_idx ON template_campo (template_planilha_id);
CREATE INDEX template_campo_campo_idx ON template_campo (campo_canonico_id);
CREATE INDEX regra_negocio_cliente_config_idx ON regra_negocio_cliente (cliente_tipo_laudo_id);
CREATE INDEX imovel_tipologia_idx ON imovel (tipologia_id);
CREATE INDEX ordem_servico_cliente_idx ON ordem_servico (cliente_id);
CREATE INDEX ordem_servico_tipo_idx ON ordem_servico (tipo_laudo_id);
CREATE INDEX ordem_servico_email_idx ON ordem_servico (email_recebido_id);
CREATE INDEX ordem_servico_imovel_idx ON ordem_servico (imovel_id);
CREATE INDEX evento_os_ordem_servico_idx ON evento_os (ordem_servico_id);
CREATE INDEX evento_os_usuario_idx ON evento_os (usuario_id);
CREATE INDEX os_pessoa_ordem_servico_idx ON os_pessoa (ordem_servico_id);
CREATE INDEX os_pessoa_pessoa_idx ON os_pessoa (pessoa_id);
CREATE INDEX imovel_atributo_imovel_idx ON imovel_atributo (imovel_id);
CREATE INDEX imovel_atributo_campo_idx ON imovel_atributo (campo_canonico_id);
CREATE INDEX agenda_disponibilidade_vistoriador_idx ON agenda_disponibilidade (vistoriador_id);
CREATE INDEX vistoriador_regiao_vistoriador_idx ON vistoriador_regiao (vistoriador_id);
CREATE INDEX vistoria_ordem_servico_idx ON vistoria (ordem_servico_id);
CREATE INDEX vistoria_vistoriador_idx ON vistoria (vistoriador_id);
CREATE INDEX tentativa_contato_vistoria_idx ON tentativa_contato (vistoria_id);
CREATE INDEX tentativa_contato_pessoa_idx ON tentativa_contato (pessoa_id);
CREATE INDEX vistoria_foto_vistoria_idx ON vistoria_foto (vistoria_id);
CREATE INDEX coleta_fonte_idx ON coleta (fonte_pesquisa_id);
CREATE INDEX amostra_fonte_idx ON amostra (fonte_pesquisa_id);
CREATE INDEX amostra_coleta_idx ON amostra (coleta_id);
CREATE INDEX amostra_tipologia_idx ON amostra (tipologia_id);
CREATE INDEX amostra_atributo_amostra_idx ON amostra_atributo (amostra_id);
CREATE INDEX amostra_atributo_campo_idx ON amostra_atributo (campo_canonico_id);
CREATE INDEX laudo_ordem_servico_idx ON laudo (ordem_servico_id);
CREATE INDEX laudo_vistoria_idx ON laudo (vistoria_id);
CREATE INDEX laudo_avaliador_idx ON laudo (avaliador_id);
CREATE INDEX laudo_template_idx ON laudo (template_planilha_id);
CREATE INDEX laudo_amostra_laudo_idx ON laudo_amostra (laudo_id);
CREATE INDEX laudo_amostra_amostra_idx ON laudo_amostra (amostra_id);
CREATE INDEX laudo_versao_laudo_idx ON laudo_versao (laudo_id);
CREATE INDEX laudo_arquivo_laudo_idx ON laudo_arquivo (laudo_id);
CREATE INDEX laudo_arquivo_versao_idx ON laudo_arquivo (laudo_versao_id);
CREATE INDEX laudo_validacao_laudo_idx ON laudo_validacao (laudo_id);
CREATE INDEX laudo_validacao_regra_idx ON laudo_validacao (regra_negocio_cliente_id);
CREATE INDEX entrega_laudo_idx ON entrega (laudo_id);
CREATE INDEX entrega_versao_idx ON entrega (laudo_versao_id);

COMMIT;
